# Generated by Django 5.1.2 on 2024-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maincompetition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reportcompetition',
            table=None,
        ),
    ]
