# Generated by Django 5.1.2 on 2024-10-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_maincompetition_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcompetition',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='recordcompetition',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='recordcompetition',
            name='reimbursement_proof_url',
        ),
    ]
