# Generated by Django 5.1.2 on 2024-11-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_recordcompetition_certificate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcompetition',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
