# Generated by Django 5.1.2 on 2024-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='手机号码', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='身份', max_length=7),
        ),
    ]
